### ISSUE TITLE
Changing to three.js instead of Chart.js

### ISSUE THREAD

**Issue by Flareux** [benhar-dev/tchmi-npm-packages#1]
I'm not quite familiar with npm packages etc. but i followed your guide to use "npm run change-deps" and install three.js which was a succes. Also i updated the index.js for three.js, however once i npm run build i get the following error 

`C:\[removed]\tchmi-npm-packages> npm run build

> buildNpmPackages@1.0.0 build
> npx webpack

assets by status 0 bytes [cached] 1 asset

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in main
Module not found: Error: Can't resolve './src' in 'C:\[removed]\tchmi-npm-packages'
resolve './src' in 'C:\[removed]tchmi-npm-packages'
  using description file: C:\[removed]\tchmi-npm-packages\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\[removed]\tchmi-npm-packages\package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\[removed]\tchmi-npm-packages\src doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\[removed]\tchmi-npm-packages\src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\[removed]\tchmi-npm-packages\src.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        C:\[removed]\tchmi-npm-packages\src.wasm doesn't exist
      as directory
        C:\[removed]\tchmi-npm-packages\src doesn't exist

webpack 5.89.0 compiled with 1 error and 1 warning in 147 ms

C:\Users\css\Documents\GitHub\tchmi-npm-packages>
` 

I am not entirely sure what is going wrong, would you be as kind to guide me in the right direction?

**Comment by benhar-dev** [comment]
Hi @Flareux, can you share the code you have added to index.js?

If I perform the same on mine then all works as expected.  Just note, the third red box is actually "npm run change-deps", for some reason it only showed the command behind the scenes.  

![image](https://github.com/benhar-dev/tchmi-npm-packages/assets/53424421/d4f10839-e782-4aef-a47f-cfb2fefadb74)

**Comment by Flareux** [comment]
Thank you very much for providing the screenshot, it seemed that i had gotten the import wrong in the index.js. Thanks for replying so fast, it's very nice of you.

**Comment by benhar-dev** [comment]
You're welcome @Flareux.  Happy coding!  (Especially with Three.  Funny enough, that's the reason I wrote this tool.  I only made the example as chart.js instead of three.js as I thought it would be easier for people to understand).

**Comment by Flareux** [comment]
Thanks!, yeah i'd love if i could get some renders inside my project for visualizing different aspects of the machine, however i'm finding it quite hard to get it work inside my HTML host, since i'm not very familiar javascript and html. I've made a few functions and animations, however getting three.js to work in TE2000 has taken me on quite a ride (working on getting better...) Do you happen to have some tips? 
Because installing it under import and then adding a html host and trying to add a simple scene with a cube from their documentation unfortunately haven't gotten me anywhere...
